# Generated by Django 4.2.11 on 2024-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
